[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  CI = "true"
  GENERATE_SOURCEMAP = "true"

# Redirect everything to index.html for client-side
# routing in Single Page Applications.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
